#!/bin/sh

# Copyright (C) 2005-2017 The RTAI project
# This [file] is free software; the RTAI project
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



ACLOCAL=aclocal
AUTOMAKE=automake

die() {
	echo
	echo "error: $1";
	echo
	exit -1;
}

echo

echo -n "running libtoolize..."
libtoolize -c --automake
if [ "$?" != "0" ]; then die "running libtoolize"; fi
echo "done"

echo -n "running aclocal..."
if test -r acinclude.m4 ; then
   touch acinclude.m4
   $ACLOCAL
else
   $ACLOCAL -I base/config/autoconf
fi
if [ "$?" != "0" ] ; then die "running aclocal"; fi
echo "done"

echo -n "running autoconf..."
autoconf
if [ "$?" != "0" ]; then die "running autoconf"; fi
echo "done"

echo -n "running autoheader..."
autoheader
if [ "$?" != "0" ]; then die "running autoheader"; fi
echo "done"

echo -n "running automake..."
$AUTOMAKE -a -c
if [ "$?" != "0" ]; then die "running automake"; fi
echo "done"

echo
